spring:
  datasource:
    url: jdbc:h2:mem:dividend
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
  redis:
    host: localhost
    port: 6379
  jwt:
    secret: aG9uZ3NhLXByb2plY3QtZGl2aWRlbmQK

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"

logging:
  config: classpath:logback-spring.xml

